package br.com.delphos.billing.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-04T13:03:45.328-02:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://servicos.billing.delphos.com.br/", name = "ServicoServer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServicoServer {

    @WebResult(name = "return", targetNamespace = "http://servicos.billing.delphos.com.br/", partName = "return")
    @WebMethod
    public java.lang.String sayHello(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://servicos.billing.delphos.com.br/", partName = "return")
    @WebMethod
    public RetornoIniciarVendaCartaoCredito iniciarVendaCartaoCredito(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3,
        @WebParam(partName = "arg4", name = "arg4")
        java.lang.String arg4,
        @WebParam(partName = "arg5", name = "arg5")
        java.lang.String arg5,
        @WebParam(partName = "arg6", name = "arg6")
        java.lang.String arg6,
        @WebParam(partName = "arg7", name = "arg7")
        java.lang.String arg7,
        @WebParam(partName = "arg8", name = "arg8")
        java.lang.String arg8,
        @WebParam(partName = "arg9", name = "arg9")
        java.lang.String arg9,
        @WebParam(partName = "arg10", name = "arg10")
        java.lang.String arg10,
        @WebParam(partName = "arg11", name = "arg11")
        java.lang.String arg11,
        @WebParam(partName = "arg12", name = "arg12")
        java.lang.String arg12,
        @WebParam(partName = "arg13", name = "arg13")
        java.lang.String arg13,
        @WebParam(partName = "arg14", name = "arg14")
        java.lang.String arg14,
        @WebParam(partName = "arg15", name = "arg15")
        java.lang.String arg15,
        @WebParam(partName = "arg16", name = "arg16")
        java.lang.String arg16,
        @WebParam(partName = "arg17", name = "arg17")
        java.lang.String arg17,
        @WebParam(partName = "arg18", name = "arg18")
        java.lang.String arg18,
        @WebParam(partName = "arg19", name = "arg19")
        java.lang.String arg19,
        @WebParam(partName = "arg20", name = "arg20")
        java.lang.String arg20,
        @WebParam(partName = "arg21", name = "arg21")
        java.lang.String arg21,
        @WebParam(partName = "arg22", name = "arg22")
        java.lang.String arg22,
        @WebParam(partName = "arg23", name = "arg23")
        java.lang.String arg23
    ) throws BillingException_Exception;

    @WebResult(name = "return", targetNamespace = "http://servicos.billing.delphos.com.br/", partName = "return")
    @WebMethod
    public RetornoCancelarVenda cancelarVenda(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3,
        @WebParam(partName = "arg4", name = "arg4")
        java.lang.String arg4,
        @WebParam(partName = "arg5", name = "arg5")
        java.lang.String arg5,
        @WebParam(partName = "arg6", name = "arg6")
        java.lang.String arg6,
        @WebParam(partName = "arg7", name = "arg7")
        java.lang.String arg7,
        @WebParam(partName = "arg8", name = "arg8")
        java.lang.String arg8
    ) throws BillingException_Exception;
}
