
package br.com.delphos.billing.braspag.consulta.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PagadorQuerySoap", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PagadorQuerySoap {


    /**
     * Get the Order Data using the new Pagador plataform.
     * 
     * @param orderDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.OrderDataResponse
     */
    @WebMethod(operationName = "GetOrderData", action = "https://www.pagador.com.br/query/pagadorquery/GetOrderData")
    @WebResult(name = "GetOrderDataResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetOrderData", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetOrderData")
    @ResponseWrapper(localName = "GetOrderDataResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetOrderDataResponse")
    public OrderDataResponse getOrderData(
        @WebParam(name = "orderDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        OrderDataRequest orderDataRequest);

    /**
     * Get the Transaction Data using the new Pagador plataform.
     * 
     * @param transactionDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.TransactionDataResponse
     */
    @WebMethod(operationName = "GetTransactionData", action = "https://www.pagador.com.br/query/pagadorquery/GetTransactionData")
    @WebResult(name = "GetTransactionDataResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetTransactionData", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetTransactionData")
    @ResponseWrapper(localName = "GetTransactionDataResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetTransactionDataResponse")
    public TransactionDataResponse getTransactionData(
        @WebParam(name = "transactionDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        TransactionDataRequest transactionDataRequest);

    /**
     * Get the Customer Data using the new Pagador plataform.
     * 
     * @param customerDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.CustomerDataResponse
     */
    @WebMethod(operationName = "GetCustomerData", action = "https://www.pagador.com.br/query/pagadorquery/GetCustomerData")
    @WebResult(name = "GetCustomerDataResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetCustomerData", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetCustomerData")
    @ResponseWrapper(localName = "GetCustomerDataResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetCustomerDataResponse")
    public CustomerDataResponse getCustomerData(
        @WebParam(name = "customerDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        CustomerDataRequest customerDataRequest);

    /**
     * Get the CreditCard Data using the new Pagador plataform.
     * 
     * @param creditCardDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.CreditCardDataResponse
     */
    @WebMethod(operationName = "GetCreditCardData", action = "https://www.pagador.com.br/query/pagadorquery/GetCreditCardData")
    @WebResult(name = "GetCreditCardDataResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetCreditCardData", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetCreditCardData")
    @ResponseWrapper(localName = "GetCreditCardDataResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetCreditCardDataResponse")
    public CreditCardDataResponse getCreditCardData(
        @WebParam(name = "creditCardDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        CreditCardDataRequest creditCardDataRequest);

    /**
     * Get the Additional Data using the new Pagador plataform.
     * 
     * @param additionalDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.AdditionalDataResponse
     */
    @WebMethod(operationName = "GetAdditionalData", action = "https://www.pagador.com.br/query/pagadorquery/GetAdditionalData")
    @WebResult(name = "GetAdditionalDataResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetAdditionalData", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetAdditionalData")
    @ResponseWrapper(localName = "GetAdditionalDataResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetAdditionalDataResponse")
    public AdditionalDataResponse getAdditionalData(
        @WebParam(name = "additionalDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        AdditionalDataRequest additionalDataRequest);

    /**
     * Get the Delivery Address Data from an order using the new Pagador plataform.
     * 
     * @param addressDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.DeliveryAddressDataResponse
     */
    @WebMethod(operationName = "GetDeliveryAddressData", action = "https://www.pagador.com.br/query/pagadorquery/GetDeliveryAddressData")
    @WebResult(name = "GetDeliveryAddressDataResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetDeliveryAddressData", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetDeliveryAddressData")
    @ResponseWrapper(localName = "GetDeliveryAddressDataResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetDeliveryAddressDataResponse")
    public DeliveryAddressDataResponse getDeliveryAddressData(
        @WebParam(name = "addressDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        DeliveryAddressDataRequest addressDataRequest);

    /**
     * Get the Boleto Data using the new Pagador plataform.
     * 
     * @param boletoDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.BoletoDataResponse
     */
    @WebMethod(operationName = "GetBoletoData", action = "https://www.pagador.com.br/query/pagadorquery/GetBoletoData")
    @WebResult(name = "GetBoletoDataResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetBoletoData", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetBoletoData")
    @ResponseWrapper(localName = "GetBoletoDataResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetBoletoDataResponse")
    public BoletoDataResponse getBoletoData(
        @WebParam(name = "boletoDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        BoletoDataRequest boletoDataRequest);

    /**
     * Get the BraspagOrderId using the new Pagador plataform.
     * 
     * @param braspagOrderIdDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.BraspagOrderIdDataResponse
     */
    @WebMethod(operationName = "GetBraspagOrderId", action = "https://www.pagador.com.br/query/pagadorquery/GetBraspagOrderId")
    @WebResult(name = "GetBraspagOrderIdResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetBraspagOrderId", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetBraspagOrderId")
    @ResponseWrapper(localName = "GetBraspagOrderIdResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetBraspagOrderIdResponse")
    public BraspagOrderIdDataResponse getBraspagOrderId(
        @WebParam(name = "braspagOrderIdDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        BraspagOrderIdDataRequest braspagOrderIdDataRequest);

    /**
     * Get the collection of BraspagOrderId with nested BraspagTransactionIds associated to an MerchantOrderId using the new Pagador plataform.
     * 
     * @param orderIdDataRequest
     * @return
     *     returns br.com.delphos.billing.braspag.consulta.cliente.OrderIdDataResponse
     */
    @WebMethod(operationName = "GetOrderIdData", action = "https://www.pagador.com.br/query/pagadorquery/GetOrderIdData")
    @WebResult(name = "GetOrderIdDataResult", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
    @RequestWrapper(localName = "GetOrderIdData", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetOrderIdData")
    @ResponseWrapper(localName = "GetOrderIdDataResponse", targetNamespace = "https://www.pagador.com.br/query/pagadorquery", className = "br.com.delphos.billing.braspag.consulta.cliente.GetOrderIdDataResponse")
    public OrderIdDataResponse getOrderIdData(
        @WebParam(name = "orderIdDataRequest", targetNamespace = "https://www.pagador.com.br/query/pagadorquery")
        OrderIdDataRequest orderIdDataRequest);

}
