package br.com.delphos.billing.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-12T09:24:02.293-02:00
 * Generated source version: 2.7.17
 * 
 */
@WebServiceClient(name = "WsImplService", 
                  wsdlLocation = "http://localhost:8080/sample-dbs-ws/services/ws?wsdl",
                  targetNamespace = "http://servicos.billing.delphos.com.br/") 
public class WsImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicos.billing.delphos.com.br/", "WsImplService");
    public final static QName WsImplPort = new QName("http://servicos.billing.delphos.com.br/", "WsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/sample-dbs-ws/services/ws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/sample-dbs-ws/services/ws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Ws
     */
    @WebEndpoint(name = "WsImplPort")
    public Ws getWsImplPort() {
        return super.getPort(WsImplPort, Ws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ws
     */
    @WebEndpoint(name = "WsImplPort")
    public Ws getWsImplPort(WebServiceFeature... features) {
        return super.getPort(WsImplPort, Ws.class, features);
    }

}
