
package br.com.delphos.billing.braspag.conciliador.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReconciliationFilesWebServiceSoap", targetNamespace = "https://reconciliation.braspag.com.br")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReconciliationFilesWebServiceSoap {


    /**
     * Obtém arquivos de venda diários do tipo, no formato e na data especificada.
     * 
     * @param request
     * @return
     *     returns br.com.delphos.billing.braspag.conciliador.cliente.GetExportedFileResponse2
     */
    @WebMethod(operationName = "GetExportedFile", action = "https://reconciliation.braspag.com.br/GetExportedFile")
    @WebResult(name = "GetExportedFileResult", targetNamespace = "https://reconciliation.braspag.com.br")
    @RequestWrapper(localName = "GetExportedFile", targetNamespace = "https://reconciliation.braspag.com.br", className = "br.com.delphos.billing.braspag.conciliador.cliente.GetExportedFile")
    @ResponseWrapper(localName = "GetExportedFileResponse", targetNamespace = "https://reconciliation.braspag.com.br", className = "br.com.delphos.billing.braspag.conciliador.cliente.GetExportedFileResponse")
    public GetExportedFileResponse2 getExportedFile(
        @WebParam(name = "request", targetNamespace = "https://reconciliation.braspag.com.br")
        GetExportedFileRequest request);

    /**
     * Obtém arquivo de conciliação na nova versão, no formato e na data especificada.
     * 
     * @param request
     * @return
     *     returns br.com.delphos.billing.braspag.conciliador.cliente.GetExportedFileV2Response2
     */
    @WebMethod(operationName = "GetExportedFileV2", action = "https://reconciliation.braspag.com.br/GetExportedFileV2")
    @WebResult(name = "GetExportedFileV2Result", targetNamespace = "https://reconciliation.braspag.com.br")
    @RequestWrapper(localName = "GetExportedFileV2", targetNamespace = "https://reconciliation.braspag.com.br", className = "br.com.delphos.billing.braspag.conciliador.cliente.GetExportedFileV2")
    @ResponseWrapper(localName = "GetExportedFileV2Response", targetNamespace = "https://reconciliation.braspag.com.br", className = "br.com.delphos.billing.braspag.conciliador.cliente.GetExportedFileV2Response")
    public GetExportedFileV2Response2 getExportedFileV2(
        @WebParam(name = "request", targetNamespace = "https://reconciliation.braspag.com.br")
        GetExportedFileV2Request request);

    /**
     * Envia um arquivo de transações para ser importado pelo Conciliador.
     * 
     * @param request
     * @return
     *     returns br.com.delphos.billing.braspag.conciliador.cliente.StoreTransactionFileResponse
     */
    @WebMethod(operationName = "SendTransactionFile", action = "https://reconciliation.braspag.com.br/SendTransactionFile")
    @WebResult(name = "SendTransactionFileResult", targetNamespace = "https://reconciliation.braspag.com.br")
    @RequestWrapper(localName = "SendTransactionFile", targetNamespace = "https://reconciliation.braspag.com.br", className = "br.com.delphos.billing.braspag.conciliador.cliente.SendTransactionFile")
    @ResponseWrapper(localName = "SendTransactionFileResponse", targetNamespace = "https://reconciliation.braspag.com.br", className = "br.com.delphos.billing.braspag.conciliador.cliente.SendTransactionFileResponse")
    public StoreTransactionFileResponse sendTransactionFile(
        @WebParam(name = "request", targetNamespace = "https://reconciliation.braspag.com.br")
        SendTransactionFileRequest request);

    /**
     * Obtém um arquivo de transações já importado para o Conciliador.
     * 
     * @param request
     * @return
     *     returns br.com.delphos.billing.braspag.conciliador.cliente.DownloadTransactionFileResponse
     */
    @WebMethod(operationName = "GetTransactionFile", action = "https://reconciliation.braspag.com.br/GetTransactionFile")
    @WebResult(name = "GetTransactionFileResult", targetNamespace = "https://reconciliation.braspag.com.br")
    @RequestWrapper(localName = "GetTransactionFile", targetNamespace = "https://reconciliation.braspag.com.br", className = "br.com.delphos.billing.braspag.conciliador.cliente.GetTransactionFile")
    @ResponseWrapper(localName = "GetTransactionFileResponse", targetNamespace = "https://reconciliation.braspag.com.br", className = "br.com.delphos.billing.braspag.conciliador.cliente.GetTransactionFileResponse")
    public DownloadTransactionFileResponse getTransactionFile(
        @WebParam(name = "request", targetNamespace = "https://reconciliation.braspag.com.br")
        GetTransactionFileRequest request);

}
